"""create initial tables

Revision ID: 0f54a9eb2a1f
Revises: 
Create Date: 2026-10-04 00:05:07.294873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f54a9eb2a1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('franchises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_franchises')),
    sa.UniqueConstraint('name', name=op.f('uq_franchises_name'))
    )
    platforms = op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platforms')),
    sa.UniqueConstraint('name', name=op.f('uq_platforms_name'))
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('franchise_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('release_year', sa.SmallInteger(), nullable=True),
    sa.Column('release_month', sa.SmallInteger(), nullable=True),
    sa.Column('release_note', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('unplayed', 'playing', 'finished', 'skip', name='game_status'), server_default='unplayed', nullable=False),
    sa.Column('finished_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('backloggd_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('release_month BETWEEN 1 AND 12', name=op.f('ck_games_release_month_range')),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], name=op.f('fk_games_franchise_id_franchises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_index(op.f('ix_games_franchise_id'), 'games', ['franchise_id'], unique=False)
    op.create_table('game_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_links_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_links'))
    )
    op.create_index(op.f('ix_game_links_game_id'), 'game_links', ['game_id'], unique=False)
    op.create_table('game_platforms',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_platforms_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_game_platforms_platform_id_platforms')),
    sa.PrimaryKeyConstraint('game_id', 'platform_id', name=op.f('pk_game_platforms'))
    )
    # ### end Alembic commands ###

    # Starting list of platforms (from the legacy app), in display order.
    op.bulk_insert(platforms, [
        {"name": name, "sort_order": i}
        for i, name in enumerate(INITIAL_PLATFORMS, start=1)
    ])


INITIAL_PLATFORMS = [
    "PC", "PS5", "PS4", "PS3", "PS2", "PS1", "PSP", "Vita",
    "Xbox Series", "Xbox One", "Xbox 360", "Xbox",
    "Switch 2", "Switch", "Wii U", "Wii", "GameCube", "N64", "SNES", "NES",
    "Game Boy", "GBC", "GBA", "DS", "3DS",
    "Genesis", "Sega CD", "Dreamcast", "PC Engine", "MSX", "Mobile",
]


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_platforms')
    op.drop_index(op.f('ix_game_links_game_id'), table_name='game_links')
    op.drop_table('game_links')
    op.drop_index(op.f('ix_games_franchise_id'), table_name='games')
    op.drop_table('games')
    op.drop_table('platforms')
    op.drop_table('franchises')
    # ### end Alembic commands ###
