"""replace release_note with release_tba

Revision ID: 20155d4c5ce2
Revises: 0f54a9eb2a1f
Create Date: 2026-10-04 09:12:33.448950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20155d4c5ce2'
down_revision: Union[str, Sequence[str], None] = '0f54a9eb2a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('release_tba', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # Carry the information over before dropping the old column. Any other note
    # (e.g. "Early Access") is dropped on purpose: the release date is the full launch.
    op.execute("UPDATE games SET release_tba = TRUE WHERE release_note LIKE '%TBA%'")
    op.drop_column('games', 'release_note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('release_note', mysql.VARCHAR(length=50), nullable=True))
    op.execute("UPDATE games SET release_note = 'TBA' WHERE release_tba")
    op.drop_column('games', 'release_tba')
    # ### end Alembic commands ###
