"""add games.length_hours

Revision ID: 99e6990339f8
Revises: 62600d13e7ec
Create Date: 2026-10-10 14:55:37.060672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e6990339f8'
down_revision: Union[str, Sequence[str], None] = '62600d13e7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('length_hours', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###
    # Added by hand: autogenerate doesn't detect CHECK constraints.
    op.create_check_constraint(op.f('ck_games_length_hours_range'), 'games', 'length_hours BETWEEN 1 AND 999')


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f('ck_games_length_hours_range'), 'games', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'length_hours')
    # ### end Alembic commands ###
