"""add games.play_on_id

Revision ID: 91d0d4345377
Revises: 20155d4c5ce2
Create Date: 2026-10-04 09:42:29.622122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d0d4345377'
down_revision: Union[str, Sequence[str], None] = '20155d4c5ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('play_on_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_games_play_on_id'), 'games', ['play_on_id'], unique=False)
    op.create_foreign_key(op.f('fk_games_play_on_id_platforms'), 'games', 'platforms', ['play_on_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_games_play_on_id_platforms'), 'games', type_='foreignkey')
    op.drop_index(op.f('ix_games_play_on_id'), table_name='games')
    op.drop_column('games', 'play_on_id')
    # ### end Alembic commands ###
